In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[445, 4365, 55, 5955],
 [445, 4365, 55, 6335],
 [445, 5200, 55, 3090],
 [7036, 9911, 8610, 4581, 3112],
 [7036, 9911, 8610, 4581, 9188],
 [6316, 445, 3858, 55, 2147],
 [8910, 2616, 4557, 4581]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
# To ensure all the sentences are of same length, we will use padding
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  445 4365   55 5955]
 [   0    0    0    0  445 4365   55 6335]
 [   0    0    0    0  445 5200   55 3090]
 [   0    0    0 7036 9911 8610 4581 3112]
 [   0    0    0 7036 9911 8610 4581 9188]
 [   0    0    0 6316  445 3858   55 2147]
 [   0    0    0    0 8910 2616 4557 4581]]


In [11]:
## feature representation
dim=10

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,)))
model.compile(optimizer='adam', loss='mse')
model.summary()


e:\DL_Project\IMDB\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[[ 1.30381919e-02,  1.01660602e-02, -4.30835597e-02,
         -2.32703686e-02, -3.13375816e-02,  2.25417726e-02,
          4.47474234e-02, -3.13520432e-05, -4.21581417e-03,
         -4.04808521e-02],
        [ 1.30381919e-02,  1.01660602e-02, -4.30835597e-02,
         -2.32703686e-02, -3.13375816e-02,  2.25417726e-02,
          4.47474234e-02, -3.13520432e-05, -4.21581417e-03,
         -4.04808521e-02],
        [ 1.30381919e-02,  1.01660602e-02, -4.30835597e-02,
         -2.32703686e-02, -3.13375816e-02,  2.25417726e-02,
          4.47474234e-02, -3.13520432e-05, -4.21581417e-03,
         -4.04808521e-02],
        [ 1.30381919e-02,  1.01660602e-02, -4.30835597e-02,
         -2.32703686e-02, -3.13375816e-02,  2.25417726e-02,
          4.47474234e-02, -3.13520432e-05, -4.21581417e-03,
         -4.04808521e-02],
        [ 4.91177700e-02,  3.42256092e-02, -4.99038771e-03,
          2.04825886e-02,  4.59488481e-03,  8.34940746e-03,
         -3.16558033e-02,  2.90685035e-02, -4.668694

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0,  445, 4365,   55, 5955], dtype=int32)

In [20]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


array([[[ 1.3038192e-02,  1.0166060e-02, -4.3083560e-02, -2.3270369e-02,
         -3.1337582e-02,  2.2541773e-02,  4.4747423e-02, -3.1352043e-05,
         -4.2158142e-03, -4.0480852e-02],
        [ 1.3038192e-02,  1.0166060e-02, -4.3083560e-02, -2.3270369e-02,
         -3.1337582e-02,  2.2541773e-02,  4.4747423e-02, -3.1352043e-05,
         -4.2158142e-03, -4.0480852e-02],
        [ 1.3038192e-02,  1.0166060e-02, -4.3083560e-02, -2.3270369e-02,
         -3.1337582e-02,  2.2541773e-02,  4.4747423e-02, -3.1352043e-05,
         -4.2158142e-03, -4.0480852e-02],
        [ 1.3038192e-02,  1.0166060e-02, -4.3083560e-02, -2.3270369e-02,
         -3.1337582e-02,  2.2541773e-02,  4.4747423e-02, -3.1352043e-05,
         -4.2158142e-03, -4.0480852e-02],
        [ 4.9117770e-02,  3.4225609e-02, -4.9903877e-03,  2.0482589e-02,
          4.5948848e-03,  8.3494075e-03, -3.1655803e-02,  2.9068504e-02,
         -4.6686947e-02,  3.4287084e-02],
        [-3.1724535e-02,  1.2312043e-02, -4.9718466e-02,  1.